- type: entity
  parent: BaseMachineCircuitboard
  id: StasisOperatingTableCircuitboard
  name: stasis operating table board
  description: A machine board for a stasis operating table.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: StasisOperatingTable
    stackRequirements:
      Cable: 6
      Silver: 2
      Steel: 6
      Manipulator: 2

- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: document printer machine board
  description: A machine printed circuit board for an document printer
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        Manipulator: 4
        Glass: 1
